## 배열의 생성 및 조작

In [3]:
# np.array() : 배열 생성
import numpy as np

list1 = [1, 2, 3]
arr1 = np.array(list1)

# 초기화할 값을 지정하여 배열 생성
arr2 = np.array([1, 2, 3])

# 수의 순차적인 증감을 이용하여 배열 생성

arr3 = np.arange(10)
arr3 = np.arange(0, 10, 1)
arr4 = np.arange(1, 10)
arr5 = np.arange(1, 10, 2)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)


[1 2 3]
[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


# 3. np.zeros() - 0 으로 초기화된 배열 생성 

In [7]:
# 1차원 배열
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# 2차원 배열
# np.zeros((행, 열))
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# 3차원 배열
# np.zeros((층, 행, 열))
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# 4. np.ones() - 1로 초기화된 배열 생성

In [10]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

# 5. np.random.rand() - 랜덤값 배열 생성
 - 0이상~1미만 사이의 무작위 수로 배열 생성    

In [12]:
np.random.rand(2, 3)

array([[0.55392796, 0.65581094, 0.61975131],
       [0.3526636 , 0.32611869, 0.65614497]])

# 6. np.empty() - 초기화 되지 않은 배열(빠름)

In [14]:
np.empty(5)

array([0., 0., 0., 0., 0.])

# 7. reshape() - 배열 차원 변형

In [13]:
arr2 = np.arange(16)
print(arr2)

# 1차원을 2차원으로 변형
arr2.reshape(4, 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])