# 최신 표준: Generator 객체 사용법

In [131]:
import numpy as np

# 1. 최신 표준 Generator 생성
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


# rng.integers(low, high, size): 정수 무작위 추출
- 내장 모듈의randint와 달리high미만(포함되지 않음)의 정수 배열을 만듭니다.size옵션에 원하는 행렬 형태(튜플)를 지정할 수 있습니다.

In [132]:
# 1 이상 46 미만(1~45)의 숫자 중 6개를 1차원 배열로 추출
lotto = rng.integers(1, 46, size=6)
print(lotto)  # 예: [12 45  3 24 18  7]

# 0 이상 10 미만의 정수로 채워진 2행 3열짜리 배열 생성
matrix_int = rng.integers(0, 10, size=(2, 3))
print(matrix_int)

[40  3  7 27 13 10]
[[9 7 5]
 [5 0 0]]


# rng.random(size): 0.0 이상 1.0 미만의 실수 추출M
- 원하는 형태(shape)의 난수 돗자리를 0~1 사이의 실수로 채울 때 사용합니다.

In [133]:
# 0.0 ~ 1.0 사이의 실수로 채워진 3행 2열 배열 생성
matrix_float = rng.random((3, 2))
print(matrix_float)

[[0.54925097 0.63292927]
 [0.76638285 0.60776144]
 [0.15627411 0.7010368 ]]


# rng.choice(a, size, replace): 샘플 추출 (복원/비복원)
- a: 선택할 대상 배열
- size: 추출할 요소 개수
- replace: True(복원), False(비복원)

In [134]:
items = ['Apple', 'Banana', 'Orange', 'Grape']

# 중복을 허용하여 2개 선택 (기본값: replace=True)
print(rng.choice(items, size=2))

# 중복 없이 3개 선택 (비복원 추출)
print(rng.choice(items, size=3, replace=False))

['Grape' 'Grape']
['Orange' 'Banana' 'Grape']


# rng.shuffle(x)/rng.permutation(x): 무작위 무작위 셔플
- shuffle: 원본 배열 자체를 내부에서 직접 뒤섞어버립니다. (반환값 없음)
- permutation: 원본 배열을 수정하지 않고, 새롭게 뒤섞인 배열을 반환합니다.

In [135]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.permutation(arr)
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 무작위 뒤섞인 배열

원본: [1 2 3 4 5]
셔플본: [4 3 5 2 1]


# 확률 분포 기반 난수 생성 (통계·머신러닝 필수)
## rng.normal(loc, scale, size): 정규 분포 (Gaussian)

In [136]:
# 평균 0, 표준편차 1인 표준정규분포를 따르는 데이터 10,000개 생성
normal_data = rng.normal(loc=0.0, scale=1.0, size=10000)
print(normal_data)

[-0.46518252  0.13618324  0.89964394 ...  1.86221777  1.61142673
 -1.35650888]


# rng.uniform(low, high, size): 균등 분포 (Uniform)
- 지정한 범위 내의 모든 실수가 동일한 확률(균등한 빈도)로 등장하는 난수 배열을 만듭니다.

In [137]:
# 10.0부터 20.0 사이에서 균등한 확률로 5개 추출
uniform_data = rng.uniform(10.0, 20.0, size=5)
print(uniform_data)

[13.99200579 10.66136635 19.80520829 18.41998799 16.21421868]


##  np.random.rand() - 랜덤값 배열
np.random 모듈은 파이썬 내장 random 함수의 기능을 확장하여 다양한 종류의 확률분포로부터 랜덤값을 생성할 수 있음

In [138]:
np.random.rand(2,3)

array([[0.20945717, 0.14361051, 0.55055057],
       [0.25140611, 0.23557221, 0.60918765]])

## 6. reshape() - 배열 차원 변형

In [139]:
arr2 = np.arange(16)
print(arr2)

# 1차원을 2차원으로 변형
arr2.reshape(4, 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
# 1차원을 3차원으로 변형
arr2.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## 배열 속성 확인 및 타입 변환

shape: 각 차원의 크기, dtype(): 데이터 타입, astype(): 데이터 타입 변환

In [141]:
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [142]:
arr2.shape

(16,)

In [143]:
arr2.dtype

dtype('int64')

In [144]:
arr2.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

## 배열의 저장과 불러오기

In [145]:
### 배열 저장하기 - np.save()
# np.save() - 배열를 파일로 저장
arr2 = np.arange(10).reshape(2, 5)
print(arr2)
# array.npy 파일로 저장
np.save('array2', arr2)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [146]:
# 배열 생성 및 전환
# 메서드 체이닝
# - 모듈.함수(). 메서드()
arr = np.arange(10).reshape(2, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [147]:
# 배열 저장하기: array.npy
np.save('array', arr)

### 배열 불러오기 - np.load()
- np.load('파일명') : 배열 불러오기

In [148]:
load_arr = np.load('array.npy')
print(load_arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


### 배열의 압축된 형식 - npz 형식
- np.savez(파일이름, 저장할_배열): 여러 개의 배열을 하나의 파일로 저장
- np.savez_compressed(파일이름, 저장할_배열): 여러 개의 배열을 압축하여 하나의 파일로 저장

In [149]:
#### 1. np.savez() - 압축된 npy 파일 생성

In [150]:
# 여러 배열 생성
arr1 = np.arange(10)
arr2 = np.arange(20).reshape(4, 5)
arr3 = np.random.rand(3, 3)

In [151]:
# 여러 배열을 하나의 파일로 저장
np.savez('multiple_arrays', first_array=arr1, second_array=arr2, third_array=arr3)

In [152]:
# 또는 이름 없이 저장
np.savez('arrays_no_names', arr1, arr2, arr3)


In [153]:
#### 2. npz 파일 불러오기 - np.load()

In [154]:
# npz 파일 불러오기
loaded_data = np.load('multiple_arrays.npz')

# 저장된 배열 이름 확인

print('117:',loaded_data.files)

117: ['first_array', 'second_array', 'third_array']


In [155]:
# 개별 배열 접근
print(loaded_data['first_array'])
print(loaded_data['second_array'])
print(loaded_data['third_array'])

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0.67813101 0.0926854  0.08736335]
 [0.05481143 0.92062456 0.23865716]
 [0.25175639 0.23962075 0.67340553]]


In [156]:
# 또는 변수로 할당
arr1_loaded = loaded_data['first_array']
arr2_loaded = loaded_data['second_array']
arr3_loaded = loaded_data['third_array']

In [157]:
# 사용 후 파일 닫기
loaded_data.close()

### 압축 저장 - np.savez_compressed()

In [158]:
# 압축하여 저장(파일 크기 절약)
np.savez_compressed('compressed_arrays', data1=arr1, data2=arr2, data3=arr3)