In [30]:
import numpy as np

# 배열의 인덱싱과 슬라이싱

## 1차원 배열의 인덱싱

In [31]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### 1. 기본 인덱싱

In [32]:
# 기본 인덱스
# 배열명[인덱스]
print(arr[5])

5


In [33]:
# 마이너스 인덱스
print(arr[-1])

15


In [34]:
# 슬라이싱: 인덱스 범위
print(arr[5:8])

[5 6 7]


### 2. 값 할당 - 배열 값 수정

In [35]:
# 하나의 값 할당
arr[5] = 100
print(arr)

[  0   1   2   3   4 100   6   7   8   9  10  11  12  13  14  15]


In [36]:
# 여러 값 할당
arr[6:8] = [200, 201]
print(arr)

[  0   1   2   3   4 100 200 201   8   9  10  11  12  13  14  15]


## 다차원 배열의 인덱싱

In [37]:
# 다차원 배열 생성 (메서드 체이닝)
arr2 = np.arange(16).reshape(4, 4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### 1. 2차원 배열 인덱싱
- 배열명[행인덱스][열인덱스]
- 배열명[행인덱스, 열인덱스]

In [38]:
# 한 행 전체 선택
print(arr2[1])

[4 5 6 7]


In [39]:
# 개별 요소 선택 -> 두 가지 방법이 있다.
# 1행 1열
print(arr2[1][1])
print(arr2[1, 1])


5
5


In [40]:
# 값 할당
arr2[1, 2] = 100
print(arr2)


[[  0   1   2   3]
 [  4   5 100   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


### 2차원 배열 슬라이싱
-배열명[s:e]
-배열명[s:e, s:e]

In [41]:
# 행 슬라이싱
print(arr2[0:2])
print(arr2[:2])

[[  0   1   2   3]
 [  4   5 100   7]]
[[  0   1   2   3]
 [  4   5 100   7]]


### 3. 2차원 슬라이싱(행과 열을 동시 지정)

In [42]:
# 특정 행과 열 선택
print(arr2[0:2, 2:4])
print(arr2[:2, 2:])

[[  2   3]
 [100   7]]
[[  2   3]
 [100   7]]


## 불리언 인덱스
### 불리언 인덱싱의 개념
1. 원본 배열과 동일한 사이즈의 불리언 배열을 만들어서 True인 요소만 선택
2. 조건을 만족하는 인덱스에는 True, 만족하지 않는 인덱스에는 False 
3. 이 불리언 배열을 인덱스로 사용하면 True 위치의 값만 반환

In [43]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
print(score_arr)

[80 90 70 65 85 95 90 80 75 80]


In [44]:
# 90점 이상인지 확인하는 불리언 배열 생성
print(score_arr >= 90)
score_arr >= 90

[False  True False False False  True  True False False False]


array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [45]:
# 90점 이상인 점수만 선택
score_arr[score_arr >= 90]

array([90, 95, 90])

In [46]:
# 불리언 인덱싱으로 값 변경
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [47]:


colors = np.array(['red', 'blue', 'green', 'yellow', 'red', 'red'])
data = np.random.randn(6, 4)
data


array([[-0.61349876,  1.0385044 , -0.64623748,  2.3932538 ],
       [ 2.74015708, -0.46854866,  0.37160854, -0.89700429],
       [-1.38038672, -0.752923  , -0.21709907,  0.81386499],
       [-1.10804495, -1.19611286, -1.37429365,  1.22489056],
       [-0.72288185,  0.59395866, -1.52874603, -1.26815639],
       [ 1.22197901, -0.86314806, -0.19665839, -0.59788106]])

# 고급 인덱싱 기법
### 팬시 인덱싱(Fancy Indexing)
- 정수 배열을 사용하여 특정 인덱스들을 선택하는 방법

In [ ]:
# 배열 생성
# np.arange([start, ]stop[, step[, dtype]])
srr = np.arange(20)
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [49]:
# 정수 리스트
indices = [1, 3, 5, 7]

In [50]:
arr[indices]

array([  1,   3, 100, 201])

In [51]:
# 2차원 배열에서 팬시 인덱싱
# 1차원 배열
arr2d = np.arange(12)
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
# 2차원 배열로 변환
arr2d = np.arange(12).reshape(3, 4)

In [60]:
# arr2d[행, 열]
# (0,1)과 (2,3) 위치의 값
print(arr2d[[0, 2], [1, 3]])

[ 1 11]


## 일반 논리 연산자: and, or, not
### 넘파이 논리 연산자: &, |, ~
 - & (앰퍼샌드, ampersand): 그리고
 - | (파이프, pipe): 또는
 - ~ (틸드, tilde): not


In [62]:
# 다중 조건 불리언 인덱싱
# 여러 조건 조합
# 배열 생성
scores = np.array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])
scores

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [ ]:
# 80점대 값만 출력? 80점이상 90점미만
# 배열[(조건식1) & (조건식2)]
# 두 조건식이 모두 True인 경우만 출력
print(scores[(scores >= 80) & (scores < 90)])

In [63]:
# 70점 미만 또는 95점 이상
# 배열[(조건식1) | (조건식2)]
# 두 조건식 중 하나 이상 True인 경우 출력
print(scores[(scores < 70) | (scores > 95)])

[65]


In [64]:
# 조건부 값 치환
# np.where(조건식, 참, 거짓)
scores

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [65]:
# 90점 이상이면 'A', 아니면 'B'
grades = np.where(scores >= 90, 'A', 'B')
print(grades)

['B' 'A' 'B' 'B' 'B' 'A' 'A' 'B' 'B' 'B']


In [66]:
# 실무 활용 예시
# 데이터 필터링
# 실제 데이터 분석에서 자주 사용되는 패턴
temperatures = np.array([22.5, 25.1, 19.8, 30.2, 28.7, 15.3, 32.1])

In [67]:
# 25도 이상인 날씨만 선택
hot_days = temperatures[temperatures >= 25.0]
print(f"25도 이상인 날씨: {hot_days}")

25도 이상인 날씨: [25.1 30.2 28.7 32.1]


In [68]:
# 20도 미만인 날씨를 20도로 조정
temperatures[temperatures < 20] = 20
print(f"조정된 온도. {temperatures}")

조정된 온도. [22.5 25.1 20.  30.2 28.7 20.  32.1]


In [69]:
# 2차원 데이터 처리
# 성적표 데이터 (학생 x 과목)
grades = np.array([
    [85, 92, 78, 90],  # 학생1
    [76, 88, 82, 79],  # 학생2
    [92, 95, 89, 94],  # 학생3
    [68, 72, 75, 71]   # 학생4
])

# 각 학생의 평균 점수가 80점 이상인 학생들
student_avg = grades.mean(axis=1)  # array([86.25, 81.25, 92.5 , 71.5 ])
good_students = grades[student_avg >= 80]  #학생1~학생3 성적
print("평균 80점 이상 학생들의 성적.")
print(good_students)

평균 80점 이상 학생들의 성적.
[[85 92 78 90]
 [76 88 82 79]
 [92 95 89 94]]


In [70]:
# 모든 과목에서 85점 이상인 점수만 추출
excellent_scores = grades[grades >= 85]
print("85점 이상 점수들.", excellent_scores)

85점 이상 점수들. [85 92 90 88 92 95 89 94]
