In [ ]:
# 배열의 연산과 변형
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [ ]:
## 벡터화 연산(Vectorized Operation)
arr + 2

array([3, 4, 5, 6])

In [4]:
arr * 2 

array([2, 4, 6, 8])

In [5]:
# 리스트
list = [1, 2, 3, 4]
list


[1, 2, 3, 4]

In [ ]:
list * 2  # +는 실행이 안됨

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [8]:
arr + arr1

array([ 6,  8, 10, 12])

In [9]:
list1 = [5, 6, 7, 8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]