In [1]:
# 배열의 연산과 변형
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [2]:
## 벡터화 연산(Vectorized Operation)
arr + 2

array([3, 4, 5, 6])

In [3]:
arr * 2 

array([2, 4, 6, 8])

In [4]:
# 리스트
list = [1, 2, 3, 4]
list


[1, 2, 3, 4]

In [5]:
list * 2  # +는 실행이 안됨

[1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [7]:
arr + arr1

array([ 6,  8, 10, 12])

In [8]:
list1 = [5, 6, 7, 8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

## 주요 산술 연산 함수
### 수학 함수들

In [9]:
# 배열 생성 (위에서 설정됨)
# list = [1, 2, 3, 4]
# arr = np.array(list)   # arr = array([1, 2, 3, 4])
# 제곱
print(np.square(arr))   # array([ 1, 4 , 9, 16])

[ 1  4  9 16]


In [10]:
# 제곱근(루트)
print(np.sqrt(arr))   # array([1.        , 1.41421356, 1.73205081, 2.        ])
 

[1.         1.41421356 1.73205081 2.        ]


In [12]:
# exp(지수승)
print(np.exp(arr))   # array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [11]:
# log
print(np.log(arr))     # array([0.        , 0.69314718, 1.09861229, 1.38629436])

[0.         0.69314718 1.09861229 1.38629436]


### 2. 배열 연산 함수들

In [14]:
# 더하기
print(np.add(arr, arr1))  # arr + arr1과 동일. array([ 6,  8, 10, 12])
# 합계
print(np.sum(arr))        # 10

# 누적합
print(np.cumsum(arr))     # array([ 1,  3,  6, 10])

[ 6  8 10 12]
10
[ 1  3  6 10]


### 3. 통계 함수들

In [15]:
# 평균
print(np.mean(arr))     # 2.5

# 편차
print(np.var(arr))      # 1.25

# 표준편차
print(np.std(arr))      # 1.118033988749895

# 최솟값
print(np.min(arr))      # 1

# 최댓값
print(np.max(arr))      # 4

# 최솟값의 인덱스
print(np.argmin(arr))   # 0

# 최댓값의 인덱스
print(np.argmax(arr))   # 3

2.5
1.25
1.118033988749895
1
4
0
3


### 배열의 변형
#### 1. 축 변환 (Transpose)

In [16]:
# 2차원 배열 생성
arr = np.arange(10).reshape(2, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
# 2차원 배열의 축 변환
# (2, 5) -> (5, 2)
print(arr.transpose())
print(arr.T)  # arr.transpose()와 동일

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
# 3차원 배열의 축 변환
# (0, 1, 2) -> (1, 0, 2)
# 1: 1번 축에 있던 '행'을 0번 축(면)으로
# 0: 0번 축에 있던 '열'을 1번 축(행)으로
# 2: 2번 축에 있던 '층'을 2번 축(열)으로
arr3d = np.arange(27).reshape(3, 3, 3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [21]:
# 특정 축 순서 지정
print(arr3d.transpose(1, 0, 2))

[[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  5]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]]


## 고급 연산 기법
### 브로드 캐스팅?
- shape이 다른 다차원배열 또는 스칼라 값 사이에서 연산이 가능

In [22]:
# 2차원 배열과 1차원 배열의 연산
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


### 축 지정 연산

In [ ]:
# 열 방향 합계 (axis=0)
print(np.sum(arr_2d, axis=0)) # [5 7 9]

# 행 방향 합계 (axis=1)
print(np.sum(arr_2d, axis=1)) # [ 6 15]

# 전체 합계
print(np.sum(arr_2d)) # 21


[5 7 9]
[ 6 15]
21


### 조건부 연산

In [24]:
# 배열 생성
arr = np.array([1, -2, 3, -4, 5])

# 절댓값: 양수화
print(np.abs(arr))  # [1 2 3 4 5]

# 조건부 연산 (np.where)
result = np.where(arr > 0, arr, 0)        # 양수는 그대로, 음수는 0으로
print(result)      # [1 0 3 0 5]

[1 2 3 4 5]
[1 0 3 0 5]


## 실무 활용 예시
### 정규화(Normalization)

In [25]:
# 데이터 정규화
data = np.array([10, 20, 30, 40, 50])

# Min-Max 정규화
normalized = (data - data.min()) / (data.max() - data.min())
print(normalized)  # [0.   0.25 0.5  0.75 1.  ]

# Z-score 정규화
z_score = (data - np.mean(data)) / np.std(data)
print(z_score)  # [-1.414  -0.707  0.    0.707  1.414]

[0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 이동평균 계산

In [ ]:
# 배열 생성
prices = np.array([100, 102, 98, 105, 103, 99, 101])

# 3일 이동평균
# np.convolve: 배열의 이동평균을 계산하는 함수
# np.ones(window): window 크기만큼의 모든 요소가 1인 배열 생성
filter_var = np.ones(3) / 3
print(filter_var)

def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='valid')

ma_3 = moving_average(prices, 3)
print(ma_3)

[0.33333333 0.33333333 0.33333333]
[100.         101.66666667 102.         102.33333333 101.        ]
